


@baseUrl = http://localhost:8500
@pdsRoute = /api/v2/pds
@authRoute = /api/v2/auth

###
GET {{baseUrl}}{{pdsRoute}}/test


### 
POST {{baseUrl}}{{authRoute}}/login
Content-Type: application/json

{
    "email" : "vahieu66@gmail.com", 
    "password" : "A12345679"
}


###
POST {{baseUrl}}{{pdsRoute}}/add 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjgzMzgyNzQ0LCJleHAiOjE2ODMzODYzNDR9.ePA7nl3nPixT5x9wW_IMQtCzuOK-zxgOa5Re2yh764g
Content-Type: application/json 

{
    
    "code": "112434",
    "price": 132435,
    "name": "Quaanf ",
    "brand": "a",
    "images" : "",
    "description": "a",
    "specs": "a",
    "quantity" : 100
}

###
PATCH  {{baseUrl}}{{pdsRoute}}/update 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjg0MTg2ODk0LCJleHAiOjE2ODQxOTA0OTR9.M5jGIRlcCtLoZpAQE11yJbL9kpC6Heur9HNgQelyT-k
Content-Type: application/json 

{
    "productId": "6462aa3897a2189c5977a1be",   
    "code": "112434",
    "price": 200000,
    "name": "Băng cuốn cổ tay cổ chân cổ",
    "brand": "TVC sports"
}
###
GET {{baseUrl}}{{pdsRoute}}/read 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjg0MTg2ODk0LCJleHAiOjE2ODQxOTA0OTR9.M5jGIRlcCtLoZpAQE11yJbL9kpC6Heur9HNgQelyT-k
Content-Type: application/json 

{
    "productId": "6462aa3897a2189c5977a1be"
}

###
GET {{baseUrl}}{{pdsRoute}}/search?key=chân
Content-Type: application/json 
###
GET {{baseUrl}}{{pdsRoute}}/sort?bestSell=-1
Content-Type: application/json 

###
@cartRoute = /api/v2/cart
//Route with Cart

###
POST {{baseUrl}}{{cartRoute}}/add 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjg0MTkwNDk2LCJleHAiOjE2ODQxOTQwOTZ9.25rMOmhl1zZIZMjKIBILYoyyL4NByP5cZgKye3x-ymk

{
    
    "productId" : "6462b2291a86f5c920d8ae8f", 
    "quantity" : 10, 
    "status": "active"
}

###//cho phép xóa nhiều product cùng lúc với seperate : "|"
DELETE {{baseUrl}}{{cartRoute}}/delete 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjg0MTg4MTU4LCJleHAiOjE2ODQxOTE3NTh9.b1uqE6MyhyLrOe_y6ssQWBvyAkRrw6lp53Tszxo18Og

{
    "productId" : "6462aa3897a2189c5977a1be"
}

###
//products --> base 64 [{productId, amount, quantity}]
POST {{baseUrl}}{{cartRoute}}/payment
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNjQ1MmQ4ZTdkMGI1NmIwMDQ4MzBjZjdmIiwiaWF0IjoxNjg0MTkwNDk2LCJleHAiOjE2ODQxOTQwOTZ9.25rMOmhl1zZIZMjKIBILYoyyL4NByP5cZgKye3x-ymk

{
    "productId" : "W3sicHJvZHVjdElkIjoiNjQ2MmIyMjkxYTg2ZjVjOTIwZDhhZThmIiwicXVhbnRpdHkiOjN9XQ==", 
    "address" : "Hà Nội - Bắc Từ Niêm - Minh Khai", 
    "number": "0987643567", 
    "amount" : "100000", 
    "bankCode" : "NCB", 
    "language": "vn", 
    "shipping" : 15000, 
    "notes" : "Cầu giấy xuân thủy hà nội", 
    "status" : 0,
    "type" : "bank",
    "pay" : "pending",
    "weight" : 450
}